
name: 💄Terraform Linter 
on: 
  push:
    branches: [feature/linter-in-terraform]

jobs:
  tflint:
    runs-on: ${{ matrix.os }}
 
    defaults:
      run:
        working-directory: main-project

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Cache plugin dir
      uses: actions/cache@v3
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: v0.44.1

    - name: Init TFLint
      run: tflint --config ../.tflint.hcl --init 
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: tflint  --config ../.tflint.hcl -f compact
      