name: Check TFLint with custom config
on: 
  push:
    branches: [feature/linter-in-terraform]

jobs:
  format-hcl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check linting of Terraform modules
      uses: devops-infra/action-tflint@v0.3
      with:
        tflint_init: "true"
        tflint_config: tflint/.tflint.hcl
        dir_filter: main-project,administrators,emails